/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n        query customer_list(\n          $limit: Int!\n          $page: Int!\n          $order_by: CustomerOrderInput\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            order_by: $order_by\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      ": typeof types.Customer_ListDocument,
    "\n        query customer_one($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      ": typeof types.Customer_OneDocument,
    "\n        query customer_many($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      ": typeof types.Customer_ManyDocument,
    "\n        query customer_many_ref(\n          $limit: Int!\n          $page: Int!\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      ": typeof types.Customer_Many_RefDocument,
    "\n        mutation mutation_customer_create_one($data: CustomerInsertInput!) {\n          customer_create_one(data: $data) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      ": typeof types.Mutation_Customer_Create_OneDocument,
    "\n        mutation mutation_customer_update(\n          $data: CustomerUpdateInput!\n          $filter: CustomerFilterInput\n        ) {\n          customer_update(data: $data, filter: $filter) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      ": typeof types.Mutation_Customer_UpdateDocument,
    "\n        mutation mutation_customer_delete($filter: CustomerFilterInput) {\n          customer_delete(filter: $filter)\n        }\n      ": typeof types.Mutation_Customer_DeleteDocument,
};
const documents: Documents = {
    "\n        query customer_list(\n          $limit: Int!\n          $page: Int!\n          $order_by: CustomerOrderInput\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            order_by: $order_by\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      ": types.Customer_ListDocument,
    "\n        query customer_one($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      ": types.Customer_OneDocument,
    "\n        query customer_many($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      ": types.Customer_ManyDocument,
    "\n        query customer_many_ref(\n          $limit: Int!\n          $page: Int!\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      ": types.Customer_Many_RefDocument,
    "\n        mutation mutation_customer_create_one($data: CustomerInsertInput!) {\n          customer_create_one(data: $data) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      ": types.Mutation_Customer_Create_OneDocument,
    "\n        mutation mutation_customer_update(\n          $data: CustomerUpdateInput!\n          $filter: CustomerFilterInput\n        ) {\n          customer_update(data: $data, filter: $filter) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      ": types.Mutation_Customer_UpdateDocument,
    "\n        mutation mutation_customer_delete($filter: CustomerFilterInput) {\n          customer_delete(filter: $filter)\n        }\n      ": types.Mutation_Customer_DeleteDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query customer_list(\n          $limit: Int!\n          $page: Int!\n          $order_by: CustomerOrderInput\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            order_by: $order_by\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      "): (typeof documents)["\n        query customer_list(\n          $limit: Int!\n          $page: Int!\n          $order_by: CustomerOrderInput\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            order_by: $order_by\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query customer_one($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      "): (typeof documents)["\n        query customer_one($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query customer_many($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      "): (typeof documents)["\n        query customer_many($filters: CustomerFilterInput) {\n          customer(filters: $filters) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query customer_many_ref(\n          $limit: Int!\n          $page: Int!\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      "): (typeof documents)["\n        query customer_many_ref(\n          $limit: Int!\n          $page: Int!\n          $filters: CustomerFilterInput\n        ) {\n          customer(\n            filters: $filters\n            pagination: { page: { limit: $limit, page: $page } }\n          ) {\n            nodes {\n              id: customer_id\n              title\n              first_name\n              middle_name\n              last_name\n              name_style\n              suffix\n              company_name\n              sales_person\n              email_address\n              phone\n              rowguid\n              created_date\n            }\n            pagination_info {\n              current\n              pages\n              offset\n              total\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation mutation_customer_create_one($data: CustomerInsertInput!) {\n          customer_create_one(data: $data) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      "): (typeof documents)["\n        mutation mutation_customer_create_one($data: CustomerInsertInput!) {\n          customer_create_one(data: $data) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation mutation_customer_update(\n          $data: CustomerUpdateInput!\n          $filter: CustomerFilterInput\n        ) {\n          customer_update(data: $data, filter: $filter) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      "): (typeof documents)["\n        mutation mutation_customer_update(\n          $data: CustomerUpdateInput!\n          $filter: CustomerFilterInput\n        ) {\n          customer_update(data: $data, filter: $filter) {\n            id: customer_id\n            title\n            first_name\n            middle_name\n            last_name\n            name_style\n            suffix\n            company_name\n            sales_person\n            email_address\n            phone\n            rowguid\n            created_date\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation mutation_customer_delete($filter: CustomerFilterInput) {\n          customer_delete(filter: $filter)\n        }\n      "): (typeof documents)["\n        mutation mutation_customer_delete($filter: CustomerFilterInput) {\n          customer_delete(filter: $filter)\n        }\n      "];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;