/* tslint:disable */
/* eslint-disable */
/**
 * sea-orm-pro-frontend-ra
 * FrontEnd React-Admin for backend sea-orm-pro
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: oizhaolei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CurrentResponse
 */
export interface CurrentResponse {
    /**
     * 
     * @type {string}
     * @memberof CurrentResponse
     */
    'pid': string;
    /**
     * 
     * @type {string}
     * @memberof CurrentResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CurrentResponse
     */
    'email': string;
    /**
     * 
     * @type {Array<Permission>}
     * @memberof CurrentResponse
     */
    'permissions': Array<Permission>;
}
/**
 * 
 * @export
 * @interface DashboardBody
 */
export interface DashboardBody {
    /**
     * 
     * @type {string}
     * @memberof DashboardBody
     */
    'graph': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardBody
     */
    'from'?: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardBody
     */
    'to'?: string;
}
/**
 * 
 * @export
 * @interface DashboardDatum
 */
export interface DashboardDatum {
    /**
     * 
     * @type {string}
     * @memberof DashboardDatum
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardDatum
     */
    'val': string;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    'is_verified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'pid': string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface PasswordLoginParams
 */
export interface PasswordLoginParams {
    /**
     * 
     * @type {string}
     * @memberof PasswordLoginParams
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof PasswordLoginParams
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    'subject': string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    'object': string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    'action'?: string;
}

/**
 * AdminsApi - axios parameter creator
 * @export
 */
export const AdminsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Graph data for dashboard
         * @summary Graph data for dashboard
         * @param {DashboardBody} dashboardBody dashboard
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboard: async (dashboardBody: DashboardBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dashboardBody' is not null or undefined
            assertParamExists('dashboard', 'dashboardBody', dashboardBody)
            const localVarPath = `/api/admin/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dashboardBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminsApi - functional programming interface
 * @export
 */
export const AdminsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminsApiAxiosParamCreator(configuration)
    return {
        /**
         * Graph data for dashboard
         * @summary Graph data for dashboard
         * @param {DashboardBody} dashboardBody dashboard
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboard(dashboardBody: DashboardBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DashboardDatum>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboard(dashboardBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminsApi.dashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminsApi - factory interface
 * @export
 */
export const AdminsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminsApiFp(configuration)
    return {
        /**
         * Graph data for dashboard
         * @summary Graph data for dashboard
         * @param {DashboardBody} dashboardBody dashboard
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboard(dashboardBody: DashboardBody, options?: RawAxiosRequestConfig): AxiosPromise<Array<DashboardDatum>> {
            return localVarFp.dashboard(dashboardBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminsApi - object-oriented interface
 * @export
 * @class AdminsApi
 * @extends {BaseAPI}
 */
export class AdminsApi extends BaseAPI {
    /**
     * Graph data for dashboard
     * @summary Graph data for dashboard
     * @param {DashboardBody} dashboardBody dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminsApi
     */
    public dashboard(dashboardBody: DashboardBody, options?: RawAxiosRequestConfig) {
        return AdminsApiFp(this.configuration).dashboard(dashboardBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Try to login via a User in the database.
         * @summary Login
         * @param {PasswordLoginParams} passwordLoginParams login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (passwordLoginParams: PasswordLoginParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passwordLoginParams' is not null or undefined
            assertParamExists('login', 'passwordLoginParams', passwordLoginParams)
            const localVarPath = `/api/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passwordLoginParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Try to login via a User in the database.
         * @summary Login
         * @param {PasswordLoginParams} passwordLoginParams login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(passwordLoginParams: PasswordLoginParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(passwordLoginParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Try to login via a User in the database.
         * @summary Login
         * @param {PasswordLoginParams} passwordLoginParams login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(passwordLoginParams: PasswordLoginParams, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(passwordLoginParams, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Try to login via a User in the database.
     * @summary Login
     * @param {PasswordLoginParams} passwordLoginParams login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(passwordLoginParams: PasswordLoginParams, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(passwordLoginParams, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Tries to get single user by username from the database
         * @summary Get single User by username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profile: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Tries to get single user by username from the database
         * @summary Get single User by username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profile(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profile(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * Tries to get single user by username from the database
         * @summary Get single User by username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profile(options?: RawAxiosRequestConfig): AxiosPromise<CurrentResponse> {
            return localVarFp.profile(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * Tries to get single user by username from the database
     * @summary Get single User by username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public profile(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profile(options).then((request) => request(this.axios, this.basePath));
    }
}



