/* tslint:disable */
/* eslint-disable */
/**
 * rust-axum-sqlx-redis-ws-template
 * Rust+Axum+Sqlx+Redis+Postgres Web Service Template
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: krzysztof.grajek@softwaremill.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

